### ISSUE TITLE
url to a script should be bookmarkable

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-pipes-editor#13]
If i open an s-pipes script it shows url that is not possible to share. If i enter this url into next tab/window it shows an empty page. The best solution would be to share concrete view of the script (or its copy), less optimal would be to share the script  without the view.

**Comment by YanDoroshenko** [comment]
Resolved in [8be84268916c80e3ecde143e238803b07c6bbc54](https://github.com/kbss-cvut/s-pipes-editor/commit/8be84268916c80e3ecde143e238803b07c6bbc54).
