### ISSUE TITLE
script shows strange ask expression

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-pipes-editor#14]
Within gacr-model, the  generated configuration form of module bind-descriptor-type-id for script ..../descriptor/spo-summary/transformation.ttl shows strange value for property "http://onto.fel.cvut.cz/ontologies/lib/module/has-input-graph-constraint" i.e.:
`<http://spinrdf.org/sp#Ask>([])`

This value is inherited from definition in .../descriptor/transformation-core.ttl where there are following triples:
```
descriptor-script:bind-descriptor-type-id
  rdf:type sml:BindWithConstant ;
  **kbss-module:has-input-graph-constraint [
      rdf:type sp:Ask ;
      sp:where (
          [
            rdf:type sp:Filter ;
            sp:expression [
                rdf:type sp:not ;
                sp:arg1 [
                    rdf:type sp:bound ;
                    sp:arg1 [
                        sp:varName "descriptorType" ;
                      ] ;
                  ] ;
              ] ;
          ]
        ) ;**
    ] ;
```
Thus correct value of property "http://onto.fel.cvut.cz/ontologies/lib/module/has-input-graph-constraint" should be :
```
ASK WHERE {
    FILTER (!bound(?descriptorType)) .
}
```

**Comment by YanDoroshenko** [comment]
Looks like a syntax error in the TTL - expression is not parsed correctly and SPINExpressions does not recognize it:
![image](https://user-images.githubusercontent.com/13915536/41970457-3d79dc20-7a0b-11e8-9c5c-a979ee5ebd0e.png)
![image](https://user-images.githubusercontent.com/13915536/41970464-44942452-7a0b-11e8-9471-c9e4e7784b73.png)

**Comment by YanDoroshenko** [comment]
@blcham Can you take a look, please?

**Comment by blcham** [comment]
It seems like you are using wrong API to parse the query. ASK expression is not SPIN expression but SPIN query in a same way CONSTRUCT expression or SELECT expression is SPIN query. Thus, I think  `SPINExpressions.isExpression(st.getObject())` would return `false`. 

You need to parse it in a same way as it is parsed in s-pipes-forms -- I have created test for it in `AnonNodeTransformerTest.serializeForAskWithoutTextReturnsTextRepresentation()`.

**Comment by blcham** [comment]
I found older version of class `AnonNodeTransformer.java` where test is working. It is in s-pipes commit d380031c712895199e6828157b279382f135803f. See file in the
[old-source-file-that-works.zip](https://github.com/kbss-cvut/s-pipes-editor/files/2166056/old-source-file-that-works.zip)
 attachement.

**Comment by YanDoroshenko** [comment]
Resolved in s-pipes-forms.
