### ISSUE TITLE
list of scripts should be organized in a tree

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-pipes-editor#15]
List of scripts should be organized in a tree component, so they show directory structure. A smarter tree component view would be good for future development (e.g. drag-n-drop feature to organize files correctly). 
A list of reactjs tree view components, not necessarily good one, is here.:
`https://react.rocks/tag/TreeView`

**Comment by YanDoroshenko** [comment]
Resolved in [f92e9ef7c4314a66fec10c0aa7d85b8ca9195dfa](https://github.com/kbss-cvut/s-pipes-editor/commit/f92e9ef7c4314a66fec10c0aa7d85b8ca9195dfa).
