### ISSUE TITLE
an attribute sml:replace appears twice in a configuration of module

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-pipes-editor#16]
Within generated configuration form of module "compute-endpoint-statistics" in script gacr-model/.../script spo-summary/transformation.ttl,  there are two generated fields for the property "http://topbraid.org/sparqlmotionlib#replace". Only one slot for the property should be generated.

**Comment by YanDoroshenko** [comment]
Resolved in semantic-pipes-forms.
