### ISSUE TITLE
Command line run

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-pipes-editor#18]
Implement a possibility to run the editor from the command line (possibly using Jetty). 
Command line parameters:

- Configuration flie `.spipesconfig` to use (if none, find in the parent directories)
- File to open for editing (if none - open the script locations file tree)

**Comment by YanDoroshenko** [comment]
Resolved in [36a16e35bf980d539b909b6a75e7e524e6ba767d](https://github.com/kbss-cvut/s-pipes-editor/commit/36a16e35bf980d539b909b6a75e7e524e6ba767d). To run the application, build the `production` profile: `mvn clean install -P production` (this is done in order not to assemble the webapp every time you run the application) and then run the exploded war using the `jetty` profile: `mvn jetty:run-exploded -P jetty`. Optionally one can pass the `-DscriptsLocation` parameter (`-DscriptLocations=/path1,/path2,/path3`) to override the script locations, specified in the `config.properties`.
