### ISSUE TITLE
sp:text should be used to save sparql queries

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-pipes-editor#23]
Generated fields of "sparql query type" within a module configuration should save answers into `sp:text` instead of using spin syntax. By "sparql query type" I mean any node that is represented by `sp:Ask`, `sp:Construct`, `sp:Select`, etc. 

An example from `16gacr/descriptor/transformation-core.ttl`:
Module `../deploy-descriptor` contains property `../has-input-graph-constraint` with content:
```
# computed descriptor is empty graph
ASK
WHERE {
    OPTIONAL {
        ?s ?p ?o .
    }
    FILTER(!bound(?s))
}
```

Currently it is saved as:
 ```
kbss-module:has-input-graph-constraint [
      rdf:type sp:Ask ;
      sp:text """# computed descriptor is empty graph
ASK
WHERE {
    OPTIONAL {
        ?s ?p ?o .
    }
    FILTER(!bound(?s))
}""" ;
      sp:where (
          [
            rdf:type sp:Optional ;
            sp:elements (
                [
....
```

This is correctly loaded into the configuration form, but it is incorrectly saved if I modify it and save it again:
```
        kbss-module:has-input-graph-constraint
                "# target descriptor graph is not defined\nASK\nWHERE {\n    FILTER(!bound(?descriptorGraphId))\n}" , "# computed descriptor is empty graph2\nASK\nWHERE {\n    OPTIONAL {\n        ?s ?p ?o .\n    }\n    FILTER(!bound(?s))\n}" ;

```

Moreover, it should be saved with only properties `rdf:type` and `sp:text` (thus e.g property `sp:where` should not be used):
```
 kbss-module:has-input-graph-constraint [
      rdf:type sp:Ask ;
      sp:text """# computed descriptor is empty graph
ASK
WHERE {
    OPTIONAL {
        ?s ?p ?o .
    }
    FILTER(!bound(?s))
}""" ;

```
It shoud be possible to do it directly through included org.topbraid/shacl java library.

Motivation:
Saving into sp:text is non-redundant and very close to new standard that replaces spin syntax (that should be done in future). 

Please test that inner comments of the queries are saved as well, i.e.:
```
 kbss-module:has-input-graph-constraint [
      rdf:type sp:Ask ;
      sp:text """# this is not inner comment
ASK
WHERE {
    # this is inner comment
    OPTIONAL {
        ?s ?p ?o .
    }
    FILTER(!bound(?s))
}""" ;

```

**Comment by YanDoroshenko** [comment]
Resolved in [c1bbaa8e5c654a20694a23aa1753e6ba944b8d91](https://github.com/kbss-cvut/s-pipes-editor/commit/c1bbaa8e5c654a20694a23aa1753e6ba944b8d91).
