### ISSUE TITLE
Sparql queries within module configuration offer relevant namespaces

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-pipes-editor#24]
While editing SPARQL queries within a module configuration of a script, it should be possible to use prefixes of the script (not its import closure !). Let's say, a user creates a SPARQL answer for a SPARQL-based question and saves it into the script file, then:

1) "SPARQL answer" encoded within sp:text property should not include prefix declaration that is already in the script file.
2) User should have a way to see what prefixes are declared within the script while editing the question. In worst case scenario it can be done by "?" tooltip of a question.

OPTIONAL:
3) "SPARQL answer" could support prefix declaration that is different from prefixes defined in the script file (or else the user will be forced to create prefix within the script) 
4) Visualization of "SPARQL answer" could support showing/hiding of all prefixes.

This should be possible to implement using an additional source of prefixes other than prefix.cc.  

See also :
- [RDF model of prefix definition](https://www.w3.org/TR/shacl/#sparql-prefixes)
- PrefixDefinition.java and SparqlQuestion.java within s-pipes-forms module.

**Comment by YanDoroshenko** [comment]
1) In case prefixes are not included in the answer (generated from sp:text), the SPARQL editor reports an error:
![image](https://user-images.githubusercontent.com/13915536/44219278-ed5acb80-a17b-11e8-9948-ecb0f7ca0c0c.png)

**Comment by YanDoroshenko** [comment]
Show only used prefixes in the editor, override the YASQE.default.Autocompleters.prefixes.appendPrefixIfNeeded function to search for prefixes in the predefined location (SparqlQuestion's property defined prefixes?) and if not found, run the original function.

**Comment by YanDoroshenko** [comment]
Resolved in [c0d0d52](https://github.com/kbss-cvut/s-pipes-editor/commit/c0d0d523e45bbc3ef5c8cc0952abefaebf1efde5).
